Feature/title category genres
n1chego/api_yamdb pull request #7
Opened 2023-01-10 13:03 UTC by psevdocoder

- доработал GenreViewSet CategoryViewSet TitleViewSet
- модель Title
- CategorySerializer, GenreSerializer, TitleWriteSerializer, TitleViewSerializer

2023-01-10 20:42 UTC, n1chego requested changes
Посмотрел вроде все, в основном по get_rating вопросы и как нам аккуратно сконнектить permissions твой и Валерия.

2023-01-10 20:42 UTC, n1chego commented on api_yamdb/api/serializers.py
> +    def get_rating(self, obj):
Почему решил переделать, уже готово было? См. ниже

2023-01-10 20:42 UTC, n1chego commented on api_yamdb/api/serializers.py
> +            return None
Базовое значение для рейтинга 0 (из документации).

2023-01-10 20:42 UTC, n1chego commented on api_yamdb/api/serializers.py
> +        r = Review.objects.filter(title=obj).aggregate(rating=Avg('score'))
По заданию возвращать нужно целое значение. AVG вроде как float вернет.

2023-01-10 20:42 UTC, n1chego commented on api_yamdb/api/permissions.py
> +class AdminOrRead(permissions.BasePermission):
Чтобы потом не было переопределения pull request от Валерия надо или твою ветку первой мержить или удалить этот permission или переназвать класс. Если кто будет мержить, обратите внимание.

2023-01-10 20:42 UTC, n1chego commented on api_yamdb/titles/models.py
> +        max_length=200,
Вроде нет ограничений на длину текста.

2023-01-10 20:42 UTC, n1chego commented on api_yamdb/api/serializers.py
> +        read_only_fields = ('review', 'author')
Спасибо!)

2023-01-10 20:42 UTC, n1chego commented on api_yamdb/api_yamdb/settings.py
> +    'django_filters',
Если установил новый модуль, обновляй пожалуйста requirements.txt.
`pip freeze > requirements.txt`

2023-01-10 20:42 UTC, n1chego commented on api_yamdb/api/serializers.py
> +class TitleWriteSerializer(serializers.ModelSerializer):
Хорошее решение)

2023-01-10 20:51 UTC, psevdocoder commented on api_yamdb/api/serializers.py
> +    def get_rating(self, obj):
git fetch не сработал, не появились изменения почему-то...
Сейчас сделал по git pull все появилось, извиняюсь, убираю. По поводу реализации тоже, согласен, прошу прощения.

2023-01-10 20:54 UTC, psevdocoder commented on api_yamdb/api/permissions.py
> +class AdminOrRead(permissions.BasePermission):
Не могу найти его permission, где он?

2023-01-10 21:00 UTC, psevdocoder commented on api_yamdb/api_yamdb/settings.py
> +    'django_filters',
Должно было запушить и его. Пакет на 8 строчке, несмотря на название приложения django-filters пакет называется djano-filter.
https://github.com/n1chego/api_yamdb/blob/6a388d4afffb94d9b2e5a3ea793dc2f2a979df4f/requirements.txt

2023-01-10 21:09 UTC, psevdocoder commented on api_yamdb/titles/models.py
> +        max_length=200,
убираю.

2023-01-10 21:40 UTC, psevdocoder commented on api_yamdb/api/serializers.py
> +        read_only_fields = ('review', 'author')
? А вот теперь я посыпался. Если поле автора на 16/11 строке уже рид онли, нужно ли его пихать в метакласс в ридонлифилдс?

2023-01-11 03:43 UTC, n1chego commented on api_yamdb/api/serializers.py
> +        read_only_fields = ('review', 'author')
Нет)

2023-01-11 03:46 UTC, n1chego commented on api_yamdb/api/serializers.py
> +    def get_rating(self, obj):
Мой косяк, надо было рассказать еще что можно мержить в обе стороны чтобы обновлять проект, потом в группе напишу

2023-01-11 03:47 UTC, n1chego commented on api_yamdb/api/permissions.py
> +class AdminOrRead(permissions.BasePermission):
У него в pull request два коммита, посмотри верхний

2023-01-11 03:53 UTC, n1chego commented on api_yamdb/api_yamdb/settings.py
> +    'django_filters',
Это я обновлял **requirements** после предыдущего твоего мержа, просто забыл тогда об этом написать. Можешь в своем текущем PR посмотреть этот файл полностью, там нету его. Но опять же он был бы если б я рассказал про обновление кода по ходу работы.

2023-01-11 19:14 UTC, n1chego commented on api_yamdb/api_yamdb/settings.py
> +    'django_filters',
Имею ввиду файл **requirements.txt** есть, а модуля **django-filter** в нем не было.

2023-01-12 15:18 UTC, closed without merging